name: weather
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: 3.16.2

dependencies:
  flutter:
    sdk: flutter

  # API
  dio: ^5.3.4
  flutter_dotenv: ^5.1.0
  pretty_dio_logger: ^1.3.1

  intl: ^0.18.1

  # UI
  gap: ^3.0.1
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  eva_icons_flutter: ^3.1.0
  cached_network_image: ^3.3.0
  flutter_screenutil: ^5.9.0

  dartz: ^0.10.1

  flutter_bloc: ^8.1.3
  injectable: ^2.3.2
  get_it: ^7.6.4

  get_storage: ^2.1.1
  go_router: ^12.1.1

  logger: ^2.0.2+1
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5

  easy_debounce: 2.0.3
  webview_flutter: ^4.4.2

  url_launcher: ^6.2.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  build_runner: 2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  mocktail: ^1.0.1
  mockito: ^5.0.15
  http_mock_adapter:
  bloc_test:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/image/
    - assets/lottie/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/app_icon.png"
  min_sdk_android: 21

import_sorter:
  emojis: true
  comments: false
  ignored_files:
    - \/lib\/*